apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmapservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmapservice
  template:
    metadata:
      labels:
        app: configmapservice
    spec:
      containers:
      - name: configmapservice
        image: cognixacr.azurecr.io/cognix/configmapservice:main
        envFrom:
        - configMapRef:
            name: configmap-cli
        - configMapRef:
            name: configmap-srv
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /backend
          name: storage-volume 
        imagePullPolicy: Always
      imagePullSecrets:
        - name: pullsecret
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: storage-volume
---
apiVersion: v1
kind: Service
metadata:
  name: configmap
spec:
  selector:
    app: configmapservice
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-volume
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-csi