apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrationservice
  template:
    metadata:
      labels:
        app: migrationservice
    spec:
      containers:
      - name: migrationservice
        image: cognixacr.azurecr.io/cognix/migrationservice:main
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: DATABASE_URL
      imagePullSecrets:
        - name: pullsecret
