# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import embed_service_pb2 as protos_dot_embed__service__pb2


class EmbedServiceStub(object):
    """Import the messages from the other file
    import "embed_requests.proto";

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmbeding = channel.unary_unary(
                '/com.embedd.EmbedService/GetEmbeding',
                request_serializer=protos_dot_embed__service__pb2.Testiamostaminchia.SerializeToString,
                response_deserializer=protos_dot_embed__service__pb2.EmbedResponse.FromString,
                )


class EmbedServiceServicer(object):
    """Import the messages from the other file
    import "embed_requests.proto";

    """

    def GetEmbeding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmbeding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbeding,
                    request_deserializer=protos_dot_embed__service__pb2.Testiamostaminchia.FromString,
                    response_serializer=protos_dot_embed__service__pb2.EmbedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.embedd.EmbedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbedService(object):
    """Import the messages from the other file
    import "embed_requests.proto";

    """

    @staticmethod
    def GetEmbeding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.embedd.EmbedService/GetEmbeding',
            protos_dot_embed__service__pb2.Testiamostaminchia.SerializeToString,
            protos_dot_embed__service__pb2.EmbedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
