# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/embed_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/embed_service.proto\x12\ncom.embedd\"4\n\x12Testiamostaminchia\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\"\x1f\n\rEmbedResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32Z\n\x0c\x45mbedService\x12J\n\x0bGetEmbeding\x12\x1e.com.embedd.Testiamostaminchia\x1a\x19.com.embedd.EmbedResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.embed_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TESTIAMOSTAMINCHIA']._serialized_start=42
  _globals['_TESTIAMOSTAMINCHIA']._serialized_end=94
  _globals['_EMBEDRESPONSE']._serialized_start=96
  _globals['_EMBEDRESPONSE']._serialized_end=127
  _globals['_EMBEDSERVICE']._serialized_start=129
  _globals['_EMBEDSERVICE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
