services:
  api:
    image: cognix:api
    build:
      context: ./backend
      args:
        service: api
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      STORAGE_PATH: /storage_volume/data
      UI_URL: http://localhost:8080/
    ports:
      - "8080:8080"
    env_file:
      - config/cocroach.env
      - config/minio.env
      - config/.env
    volumes:
      - ./backend:/backend
      - "storage_volume:/storage_volume"
    networks:
      - dev-network

  nats:
    image: nats
    restart: on-failure
    ports:
      - "4222:4222"
    networks:
      - dev-network

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - "qdrant_data:/qdrant_data"
    networks:
      - dev-network

  cockroach:
    image: cockroachdb/cockroach:latest-v23.2
    ports:
      - "26257:26257"
      - "18080:8080"
    command: start-single-node --insecure
    volumes:
      - "db_volume:/cockroach/cockroach-data"
    networks:
      - dev-network

  migration:
    image: cognix:migration
    build: migration
    volumes:
      - ./migration/versions:/versions
    env_file:
      - config/cocroach.env
    networks:
      - dev-network

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - milvus_etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
  minio:
    container_name: milvus-minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data
    ports:
      - "35723:35723"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.0.2
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus:/var/lib/milvus
    ports:
      - "19530:19530"
    depends_on:
      - "etcd"
      - "minio"


configs:
  qdrant_config:
    content: |
      log_level: INFO 

volumes:
  db_volume:
  storage_volume:
  qdrant_data:
  milvus_etcd:
  minio_data:
  milvus:


networks:
  dev-network:
    driver: bridge
    name: dev-network