services:
  api:
    image: cognix:api
    build:
      context: ./backend
      args:
        service: api
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      STORAGE_PATH: /storage_volume/data
    ports:
      - "8080:8080"
    env_file:
      - config/.env
      - config/cocroach.env
    volumes:
      - ./backend:/backend
      - "storage_volume:/storage_volume"
    networks:
      - dev-network

  nats:
    image: nats
    restart: on-failure
    ports:
      - "4222:4222"
    networks:
      - dev-network

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - "qdrant_data:/qdrant_data"
    networks:
      - dev-network

  cockroach:
    image: cockroachdb/cockroach:latest-v23.2
    ports:
      - "26257:26257"
      - "18080:8080"
    command: start-single-node --insecure
    volumes:
      - "db_volume:/cockroach/cockroach-data"
    networks:
      - dev-network

  migration:
    image: cognix:migration
    build: migration
    volumes:
      - ./migration/versions:/versions
    env_file:
      - config/.env
    networks:
      - dev-network


configs:
  qdrant_config:
    content: |
      log_level: INFO 

volumes:
  db_volume:
  storage_volume:
  qdrant_data:

networks:
  dev-network:
    driver: bridge