services:
  api:
    image: cognix:api
    build:
      context: ./backend
      args:
        service: api
      dockerfile: Dockerfile
    env_file:
      - config/.env
    volumes:
      - ./backend:/backend
    networks:
      - dev-network

  nats:
    image: nats
    restart: on-failure
    ports:
      - "4222:4222"
    networks:
      - dev-network

  cockroach:
    image: cockroachdb/cockroach:latest-v23.2
    ports:
      - "26257:26257"
      - "18080:8080"
    command: start-single-node --insecure
    volumes:
      - "db_volume:/cockroach/cockroach-data"
    networks:
      - dev-network

  migration:
    image: cognix:migration
    build: migration
    volumes:
      - ./migration/versions:/versions
    env_file:
      - config/.env
    networks:
      - dev-network


volumes:
  db_volume:

networks:
  dev-network:
    driver: bridge