version: '3.8'  # Use Docker Compose file version 3.8
networks:
  dev-net:
    driver: bridge

services:
  #embedder  
  embedder:
    # build: .
    image: embedder:latest
    container_name: embedder
    ports:
      - "50051:50051" 
    volumes:
      - ../data//models
    env_file:
      - ../config/embedder.env
    networks:
      - dev-net
    # depends_on:
    #   nats-server:
    #     condition: service_healthy
    environment:
      #PULSAR_CONNECTION_STRING: ${PULSAR_CONNECTION_STRING}
      PULSAR_CONNECTION_STRING: "pulsar://broker:6650"
      #PULSAR_CONNECTION_STRING: "pulsar://127.0.0.1:6650"
    