version: '3.5'

services:
  api:
    image: cognix:api
    build:
      context: ${BACKEND_PATH}
      args:
        service: api
      dockerfile: Dockerfile.dev
    environment:
      PORT: 8080
      STORAGE_PATH: /storage_volume/data
      UI_URL: http://localhost:8080/
    ports:
      - "8080:8080"
    env_file:
      - ${CONFIG_PATH}/cockroach.env
      - ${CONFIG_PATH}/minio.env
      - ${CONFIG_PATH}/.env
    volumes:
      - ${BACKEND_PATH}:/backend
    networks:
      - dev-network

  orchestrator:
    image: cognix:orchestrator
    build:
      context: ${BACKEND_PATH}
      args:
        service: orchestrator
      dockerfile: Dockerfile
    env_file:
      - ${CONFIG_PATH}/cockroach.env
      - ${CONFIG_PATH}/nats.env
      - ${CONFIG_PATH}/pulsar.env
      - ${CONFIG_PATH}/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${BACKEND_PATH}:/backend
    networks:
      - dev-network

  connector:
    image: cognix:connector
    build:
      context: ${BACKEND_PATH}
      args:
        service: connector
      dockerfile: Dockerfile.dev
    env_file:
      - ${CONFIG_PATH}/cockroach.env
      - ${CONFIG_PATH}/nats.env
      - ${CONFIG_PATH}/.env
    environment:
      MILVUS_URL: localhost:19530
    volumes:
      - ${BACKEND_PATH}:/backend
    networks:
      - dev-network

  migration:
    image: cognix:migration
    build: migration
    volumes:
      - ${MIGRATION_PATH}/versions:/versions
    env_file:
      - ${CONFIG_PATH}/cockroach.env
    networks:
      - dev-network

volumes:
  db_volume:
  nats-storage:

networks:
  dev-network:
    driver: bridge
    name: dev-network
