version: '3.8'  # Use Docker Compose file version 3.8

networks:
  dev-net:
    driver: bridge

services:
  embedder:
    build:
      context: ${COGNIX_PATH}
      dockerfile: docker/Dockerfile-embedder
      args:
        - COGNIX_PATH=${COGNIX_PATH}
    image: embedder:latest
    container_name: embedder
    ports:
      - "50051:50051"
    volumes:
      - ${DATA_PATH}/models:/models
    env_file:
      - ${CONFIG_PATH}/embedder.env
    networks:
      - dev-net
  
  chunker:
    build:
      context: ${COGNIX_PATH}
      dockerfile: docker/Dockerfile-chunker
      args:
        - COGNIX_PATH=${COGNIX_PATH}
    image: chunker:latest
    container_name: chunker
    volumes:
      - ${DATA_PATH}/models:/models
    env_file:
      - ${CONFIG_PATH}/chunker.env
    networks:
      - dev-net
