// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: embedd_messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbeddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Model   string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *EmbeddRequest) Reset() {
	*x = EmbeddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embedd_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbeddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddRequest) ProtoMessage() {}

func (x *EmbeddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedd_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddRequest.ProtoReflect.Descriptor instead.
func (*EmbeddRequest) Descriptor() ([]byte, []int) {
	return file_embedd_messages_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmbeddRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type EmbeddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vector []float32 `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
}

func (x *EmbeddResponse) Reset() {
	*x = EmbeddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embedd_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbeddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddResponse) ProtoMessage() {}

func (x *EmbeddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedd_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddResponse.ProtoReflect.Descriptor instead.
func (*EmbeddResponse) Descriptor() ([]byte, []int) {
	return file_embedd_messages_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type EmbeddData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content string    `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Model   string    `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Vector  []float32 `protobuf:"fixed32,4,rep,packed,name=vector,proto3" json:"vector,omitempty"`
}

func (x *EmbeddData) Reset() {
	*x = EmbeddData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embedd_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbeddData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddData) ProtoMessage() {}

func (x *EmbeddData) ProtoReflect() protoreflect.Message {
	mi := &file_embedd_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddData.ProtoReflect.Descriptor instead.
func (*EmbeddData) Descriptor() ([]byte, []int) {
	return file_embedd_messages_proto_rawDescGZIP(), []int{2}
}

func (x *EmbeddData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmbeddData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmbeddData) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbeddData) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

var File_embedd_messages_proto protoreflect.FileDescriptor

var file_embedd_messages_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x6d, 0x62,
	0x65, 0x64, 0x64, 0x22, 0x3f, 0x0a, 0x0d, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x22, 0x28, 0x0a, 0x0e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x64,
	0x0a, 0x0a, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_embedd_messages_proto_rawDescOnce sync.Once
	file_embedd_messages_proto_rawDescData = file_embedd_messages_proto_rawDesc
)

func file_embedd_messages_proto_rawDescGZIP() []byte {
	file_embedd_messages_proto_rawDescOnce.Do(func() {
		file_embedd_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_embedd_messages_proto_rawDescData)
	})
	return file_embedd_messages_proto_rawDescData
}

var file_embedd_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_embedd_messages_proto_goTypes = []interface{}{
	(*EmbeddRequest)(nil),  // 0: com.embedd.EmbeddRequest
	(*EmbeddResponse)(nil), // 1: com.embedd.EmbeddResponse
	(*EmbeddData)(nil),     // 2: com.embedd.EmbeddData
}
var file_embedd_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_embedd_messages_proto_init() }
func file_embedd_messages_proto_init() {
	if File_embedd_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_embedd_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbeddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_embedd_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbeddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_embedd_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbeddData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_embedd_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_embedd_messages_proto_goTypes,
		DependencyIndexes: file_embedd_messages_proto_depIdxs,
		MessageInfos:      file_embedd_messages_proto_msgTypes,
	}.Build()
	File_embedd_messages_proto = out.File
	file_embedd_messages_proto_rawDesc = nil
	file_embedd_messages_proto_goTypes = nil
	file_embedd_messages_proto_depIdxs = nil
}
