version: '3.8'  # Use Docker Compose file version 3.8
networks:
  dev-net:
    driver: bridge

services:
  nats-server:
    image: nats:latest  # Use the latest NATS image
    container_name: nats-server
    ports:
      - "4222:4222"  # Client connections to NATS
      - "8222:8222"  # HTTP monitoring port for NATS
      - "6222:6222"  # Cluster port for NATS
    networks:
      - dev-net


  # #embedder  
  # embedder:
  #   build: .
  #   container_name: embedder
  #   volumes:
  #     - /path/on/host/models:/app/models
  #   networks:
  #     - dev-net
  #   depends_on:
  #     nats-server:
  #       condition: service_healthy
  #   environment:
  #     #PULSAR_CONNECTION_STRING: ${PULSAR_CONNECTION_STRING}
  #     PULSAR_CONNECTION_STRING: "pulsar://broker:6650"
  #     #PULSAR_CONNECTION_STRING: "pulsar://127.0.0.1:6650"
  #   command: python ./embedd_service.py