services:
  embedder:
    build: .
    container_name: embedder
    volumes:
      - /path/on/host/models:/app/models
    networks:
      - dev-network
    # depends_on:
    #   broker:
    #     condition: service_healthy
    environment:
      PULSAR_CONNECTION_STRING: ${PULSAR_CONNECTION_STRING}
      #PULSAR_CONNECTION_STRING: "pulsar://broker:6650"
    command: python ./embedd_service.py

networks:
  dev-network:
    external: true
