# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedd_messages.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65mbedd_messages.proto\x12\ncom.embedd\"/\n\rEmbeddRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\" \n\x0e\x45mbeddResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"H\n\nEmbeddData\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0e\n\x06vector\x18\x04 \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedd_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDREQUEST']._serialized_start=37
  _globals['_EMBEDDREQUEST']._serialized_end=84
  _globals['_EMBEDDRESPONSE']._serialized_start=86
  _globals['_EMBEDDRESPONSE']._serialized_end=118
  _globals['_EMBEDDDATA']._serialized_start=120
  _globals['_EMBEDDDATA']._serialized_end=192
# @@protoc_insertion_point(module_scope)
