# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedd_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import embedd_messages_pb2 as embedd__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65mbedd_service.proto\x12\ncom.embedd\x1a\x15\x65mbedd_messages.proto2U\n\rEmbeddService\x12\x44\n\tGetEmbedd\x12\x19.com.embedd.EmbeddRequest\x1a\x1a.com.embedd.EmbeddResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedd_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDSERVICE']._serialized_start=59
  _globals['_EMBEDDSERVICE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
