# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/chunking_data.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/chunking_data.proto\x12\ncom.embedd\"\xcd\x01\n\x0c\x43hunkingData\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08site_map\x18\x02 \x01(\t\x12\x1a\n\x12search_for_sitemap\x18\x03 \x01(\x08\x12\x13\n\x0b\x64ocument_id\x18\x04 \x01(\x03\x12\'\n\tfile_type\x18\x05 \x01(\x0e\x32\x14.com.embedd.FileType\x12\x17\n\x0f\x63ollection_name\x18\x06 \x01(\t\x12\x12\n\nmodel_name\x18\x07 \x01(\t\x12\x17\n\x0fmodel_dimension\x18\x08 \x01(\x05*^\n\x08\x46ileType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03URL\x10\x01\x12\x07\n\x03PDF\x10\x02\x12\x07\n\x03RTF\x10\x03\x12\x07\n\x03\x44OC\x10\x04\x12\x07\n\x03XLS\x10\x05\x12\x07\n\x03PPT\x10\x06\x12\x07\n\x03TXT\x10\x07\x12\x06\n\x02MD\x10\x08\x42\x19Z\x17golang/core/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chunking_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027golang/core/proto;proto'
  _globals['_FILETYPE']._serialized_start=249
  _globals['_FILETYPE']._serialized_end=343
  _globals['_CHUNKINGDATA']._serialized_start=42
  _globals['_CHUNKINGDATA']._serialized_end=247
# @@protoc_insertion_point(module_scope)
