apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chunker
  template:
    metadata:
      labels:
        app: chunker
    spec:
      containers:
      - name: chunker
        image: cognixacr.azurecr.io/cognix/chunker:main
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        - name: NATS_URL
          value: "nats.nats:4222"
        imagePullPolicy: Always
      imagePullSecrets:
        - name: pullsecret
