apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestratorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestratorservice
  template:
    metadata:
      labels:
        app: orchestratorservice
    spec:
      containers:
      - name: orchestratorservice
        image: cognixacr.azurecr.io/cognix/orchestratorservice:main
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: DATABASE_URL
        - name: MESSAGING_PROVIDER
          value: "pulsar"
        - name: PULSAR_URL
          value: "pulsar://my-release-pulsar-proxy:6650/"
        imagePullPolicy: Always
      imagePullSecrets:
        - name: pullsecret

---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  selector:
    app: orchestratorservice
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-volume
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-csi